backend:
  name: github
  repo: Ir1d/OI-wiki
  open_authoring: true

# This line should *not* be indented
publish_mode: editorial_workflow

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "doc"
    identifier_field: "author"
    extension: "md"
    label: "Doc"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
